// Autogenerated by codegen.py. Do not modify.

@_implementationOnly import x10_xla_tensor_tf_ops
@_implementationOnly import x10_xla_tensor_wrapper

extension _RawXLA {

  public static func mean<
    T: TensorFlowNumeric
  >(
    _ input: Tensor<T>,
    reductionIndices: [Int64],
    keepDims: Bool
  ) -> Tensor<T> {
    defer { _fixLifetime(input) }
    return reductionIndices.withArrayRef { reductionIndices in
      return Tensor(_xlaHandle: XLATensor_mean(input.xlaHandle, reductionIndices, keepDims))
    }
  }

}
