file(TO_CMAKE_PATH "${X10_TOOLCHAIN_PATH}" X10_CMAKE_TOOLCHAIN_PATH)

find_file(X10_LIBRARY libx10.so ${X10_TOOLCHAIN_PATH} PATH_SUFFIXES usr/lib/swift/linux)

add_library(x10 IMPORTED UNKNOWN)
set_target_properties(x10 PROPERTIES IMPORTED_LOCATION ${X10_LIBRARY} 
	INTERFACE_INCLUDE_DIRECTORIES ${X10_CMAKE_TOOLCHAIN_PATH}/usr/lib/swift/x10/include)

add_library(tensorflow UNKNOWN IMPORTED)
set_target_properties(tensorflow PROPERTIES IMPORTED_LOCATION ${X10_LIBRARY} 
	INTERFACE_INCLUDE_DIRECTORIES ${X10_CMAKE_TOOLCHAIN_PATH}/usr/lib/swift/x10/include)
